### ISSUE TITLE
Melhorar a performance da animação em long-runs

### ISSUE THREAD

**Issue by vitor-sanc** [vitor-san/AI-Search-Types#6]

**Comment by Vernalhav** [comment]
A implementação do `MyScatter` é nossa? Parece que ela está redesenhando o frame toda vez que troca o passo. Como setamos `blit=True` no `FuncAnimator`, podemos otimizar isso se quisermos aprender mais sobre os Artists do matplotlib (parece que vai ser complicado).

**Comment by vitor-sanc** [comment]
Not gonna be done anymore since we're gonna just plot the final results.
